Repository Do-it-Comm-it/DoitCommit-front, pull requests merged in 2021-12, with the labels that each got.

#1 REFACTOR: reusable components / Registration process
  src/components/Atoms/DIButton.tsx
  src/components/Atoms/DIInput.tsx
  src/components/Atoms/DILabel.tsx
  src/components/Atoms/DISelector.tsx
  src/components/Atoms/DIText.tsx
  src/components/Modal/index.tsx
  src/components/Molecules/UserProfile.tsx
  src/components/Organisms/GithubLogin/index.tsx
  src/components/Organisms/GithubLogin/styles.tsx
  src/components/Organisms/GoogleLogin/index.tsx
  src/components/Organisms/GoogleLogin/styles.tsx
  src/components/Organisms/LoginModal/index.tsx
  src/components/Organisms/Modal/index.tsx
  src/components/Organisms/Modal/styles.tsx
  src/components/Organisms/RegisterModal/index.tsx
  src/hooks/useAuthentication.ts
  src/layouts/App/index.tsx
  src/pages/Home/index.tsx
  src/recoil/atom/modal.ts
  src/typings/User.ts
Labels: enhancement

#2 useDarkMode 훅 작성 / atom effect를 이용한 로컬스토리지에 theme 저장(for persisting t…
  src/hooks/useDarkMode.ts
  src/pages/Home/index.tsx
  src/recoil/atom/theme.ts
Labels: enhancement

#3 FEATURE: Add HeaderNavigation / Theme
  README.md
  client.tsx
  package-lock.json
  package.json
  src/components/Atoms/DIInput.tsx
  src/components/Molecules/Navigation.tsx
  src/components/Molecules/SearchBar.tsx
  src/components/Molecules/Toggle.tsx
  src/components/Molecules/UserProfile.tsx
  src/components/Organisms/HeaderNavigation.tsx
  src/components/Organisms/ThemeToggle.tsx
  src/hooks/useDarkMode.ts
  src/hooks/useDebounce.ts
  src/layouts/App/index.tsx
  src/pages/Home/index.tsx
  src/recoil/atom/theme.ts
  src/utils/theme.ts
Labels: enhancement

#5 BUG: header navigation url 변경 시 유지되도록 변경 & 모달이 창 크기에 맞게 centering 되도록 수정
  src/components/Organisms/Modal/styles.tsx
  src/layouts/App/index.tsx
Labels: bug

#6 FEATURE: 사이드바 구현
  src/assets/alarm.svg
  src/assets/board.svg
  src/assets/calander.svg
  src/assets/community.svg
  src/assets/darkmode.svg
  src/assets/default_profile.svg
  src/assets/doit.svg
  src/assets/hire.svg
  src/assets/language.svg
  src/assets/lightmode.svg
  src/assets/menu.svg
  src/assets/menu_extended.svg
  src/assets/option.svg
  src/assets/profile.svg
  src/assets/service.svg
  src/assets/user.svg
  src/components/Molecules/SidebarContent.tsx
  src/components/Molecules/SidebarFooter.tsx
  src/components/Molecules/SidebarTop.tsx
  src/components/Organisms/Sidebar/index.tsx
  src/data/sidebarData.tsx
  src/layouts/App/GlobalStyles.tsx
  src/layouts/App/index.tsx
Labels: enhancement

#9 FIX : 다른 라우트에서 모달을 여는 액션을 취했을 때 열리지 않는 버그 수정
  src/layouts/App/index.tsx
  src/pages/Home/index.tsx
Labels: bug

#11 FEATURE: 임시 마이페이지 작업
  src/PriavteRoute.tsx
  src/assets/edit.svg
  src/assets/user.svg
  src/components/Molecules/Navigation.tsx
  src/components/Organisms/MyPage/ProfileArea.tsx
  src/components/Organisms/MyPage/ProfileImageArea.tsx
  src/components/Organisms/MyPage/ProfileInfoArea.tsx
  src/components/Organisms/RegisterModal/index.tsx
  src/components/Organisms/SelectInput.tsx
  src/data/sidebarData.tsx
  src/data/techListData.ts
  src/layouts/App/GlobalStyles.tsx
  src/layouts/App/index.tsx
  src/pages/MyPage/index.tsx
Labels: enhancement

#12 FIX: 회의 때 나온 수정안으로 사이드바 수정
  client.tsx
  src/components/Molecules/Navigation.tsx
  src/components/Molecules/Sidebar/SidebarContent.tsx
  src/components/Molecules/Sidebar/SidebarFooter.tsx
  src/components/Molecules/Sidebar/SidebarTop.tsx
  src/components/Molecules/SidebarTop.tsx
  src/components/Organisms/Sidebar/index.tsx
  src/hooks/useAuthentication.ts
  src/layouts/App/GlobalStyles.tsx
  src/layouts/App/index.tsx
  src/routes/PriavteRoute.tsx
  src/routes/Route.tsx
  src/utils/fetcher.ts
Labels: fix

#14 FIX: User 타입 수정
  package-lock.json
  src/components/Molecules/MyPage/ProfileInfoArea.tsx
  src/components/Organisms/Modal/index.tsx
  src/hooks/useAuthentication.ts
  src/typings/User.ts
  yarn.lock
Labels: fix

#16 FEATURE: 프로필 카드 공유 기능 추가 (임시)
  package-lock.json
  package.json
  src/components/Molecules/MyPage/ProfileInfoArea.tsx
  src/components/Organisms/MyPage/ProfileArea.tsx
  src/pages/MyPage/index.tsx
  yarn.lock
Labels: enhancement

#17 REFACTOR: Fetcher
  src/components/Molecules/MyPage/ProfileInfoArea.tsx
  src/components/Organisms/RegisterModal/index.tsx
  src/hooks/useAuthentication.ts
  src/service/api.ts
  src/utils/fetcher.ts
  yarn.lock
Labels: refactor

#18 FEATURE: 회원 탈퇴 api 연결
  src/components/Organisms/MyPage/Documents.tsx
  src/components/Organisms/MyPage/PersonalSettings.tsx
  src/components/Organisms/RegisterModal/index.tsx
  src/service/api.ts
  src/utils/fetcher.ts
Labels: enhancement
