Repository Do-it-Comm-it/DoitCommit-front, pull requests merged in 2022-02, with the labels that each got.

#28 FEATURE: 유저 가입, 수정 기능 반영
  package-lock.json
  package.json
  src/components/Atoms/Mypage/index.tsx
  src/components/Molecules/MyPage/Form.tsx
  src/components/Molecules/MyPage/ProfileImageArea.tsx
  src/components/Molecules/MyPage/ProfileInfoArea.tsx
  src/components/Molecules/UserProfile.tsx
  src/components/Organisms/Modal/RegisterModal.tsx
  src/components/Organisms/Modal/index.tsx
  src/components/Organisms/SelectInput.tsx
  src/data/formData.ts
  src/recoil/atom/file.ts
  src/recoil/atom/user.ts
  src/service/api.ts
  src/typings/Tech.ts
  src/typings/User.ts
  src/utils/fetcher.ts
  yarn.lock
Labels: enhancement

#29 FIX: 반응형 홈 화면
  src/components/Molecules/Community/CommunityBox.tsx
  src/components/Molecules/ContentBox.tsx
  src/components/Molecules/Planner/PlannerBox.tsx
  src/components/Molecules/Planner/PlannerDate.tsx
  src/components/Molecules/Todo/AddTodoBox.tsx
  src/components/Molecules/Todo/TodoBox.tsx
  src/components/Organisms/Home/AdBanner.tsx
  src/components/Organisms/Home/Community.tsx
  src/components/Organisms/Home/HomeTitle.tsx
  src/components/Organisms/Home/HomeTodoList.tsx
  src/components/Organisms/Home/Planner.tsx
  src/layouts/App/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyPage/index.tsx
  yarn.lock
Labels: fix

#30 FEATURE: 투두 -> 생성 / 수정 / 삭제 / 조회
  package.json
  src/components/Molecules/ContentBox.tsx
  src/components/Molecules/MyPage/Form.tsx
  src/components/Molecules/MyPage/ProfileInfoArea.tsx
  src/components/Molecules/Planner/PlannerDate.tsx
  src/components/Molecules/Planner/PlannerLabel.tsx
  src/components/Molecules/Todo/AddTodoBox.tsx
  src/components/Molecules/Todo/TodoBox.tsx
  src/components/Molecules/TodoModal/TagContainer.tsx
  src/components/Molecules/TodoModal/TextAreaContainer.tsx
  src/components/Organisms/Home/AdBanner.tsx
  src/components/Organisms/Home/HomeTodoList.tsx
  src/components/Organisms/Modal/RegisterModal.tsx
  src/components/Organisms/Modal/TodoModal.tsx
  src/components/Organisms/Modal/index.tsx
  src/hooks/useTodo.ts
  src/layouts/App/index.tsx
  src/pages/Home/index.tsx
  src/recoil/atom/modal.ts
  src/recoil/atom/user.ts
  src/service/api.ts
  src/typings/Todos.ts
  src/utils/fetcher.ts
  yarn.lock
Labels: enhancement, fix

#32 REFACTOR: USER (recoil) -> (react-query)
  package-lock.json
  src/components/Molecules/MyPage/Form.tsx
  src/components/Molecules/MyPage/ProfileImageArea.tsx
  src/components/Molecules/MyPage/ProfileInfoArea.tsx
  src/components/Molecules/UserProfile.tsx
  src/components/Organisms/HeaderNavigation.tsx
  src/components/Organisms/Home/HomeTitle.tsx
  src/components/Organisms/Home/HomeTodoList.tsx
  src/components/Organisms/Modal/RegisterModal.tsx
  src/components/Organisms/Modal/index.tsx
  src/hooks/useAuthentication.ts
  src/hooks/useTodo.ts
  src/layouts/App/index.tsx
  src/recoil/atom/user.ts
  src/routes/PrivateRoute.tsx
  src/service/api.ts
  src/typings/User.ts
  yarn.lock
Labels: refactor

#33 FEATURE: 닉네임 중복 체크
  src/components/Organisms/Modal/RegisterModal.tsx
  src/service/api.ts
Labels: enhancement

#35 게시판 페이지 레이아웃
  package-lock.json
  package.json
  src/assets/comment.svg
  src/assets/heart.svg
  src/assets/search.svg
  src/assets/view.svg
  src/assets/write.svg
  src/components/Atoms/Board/Status.tsx
  src/components/Atoms/Board/Thumbnail.tsx
  src/components/Molecules/Board/BoardContent.tsx
  src/components/Molecules/Board/Card.tsx
  src/components/Molecules/Board/SearchBar.tsx
  src/components/Molecules/Board/Tags.tsx
  src/components/Molecules/MyPage/ProfileInfoArea.tsx
  src/components/Molecules/SearchBar.tsx
  src/components/Molecules/Sidebar/SidebarTop.tsx
  src/components/Molecules/Todo/TodoBox.tsx
  src/components/Organisms/Board/Body.tsx
  src/components/Organisms/Board/CardContainer.tsx
  src/components/Organisms/Board/FloatingButton.tsx
  src/components/Organisms/Board/Header.tsx
  src/components/Organisms/Board/Notice.tsx
  src/components/Organisms/Home/HomeTodoList.tsx
  src/components/Organisms/Modal/RegisterModal.tsx
  src/data/sidebarData.tsx
  src/hooks/useTodo.ts
  src/layouts/App/index.tsx
  src/pages/Board/index.tsx
  src/pages/MyPage/index.tsx
  src/recoil/atom/keyword.ts
  src/recoil/selector/keyword.ts
  yarn.lock
Labels: enhancement
